name: feature-branch

on:
 push:
    branches:
      - feature-branch

jobs:
  feature-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello Sreeya!"
